package com.supportportal.entity;

public enum PhaseSelection {
	  VALIDATION_FICHE_DEMANDE_PERSONNEL,
	  REDACTION_DIFFUSION_APPEL_CANDIDATURE,
	  COLLECTE_CANDIDATURES,
	  VALIDATION_SHORTLIST_CANDIDATURES,
	  ORGANISATION_ENTRETIENS_1ER_TOUR,
	  ORGANISATION_ENTRETIENS_2ND_TOUR,
	  SELECTION_CANDIDATS,
	  VISITE_MEDICALE,
	  OFFRE_EMPLOI,
	  INTEGRATION_NOUVELLE_RECRUE;
	}